version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/client
    docker:
      - image: circleci/node:12.0.0-browsers
    steps:
      - checkout
      - run: cd client
      - run: ls
      - run: yarn client
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12.0.0-browsers
    steps:
      - checkout
      - run: cd client
      - run: yarn test:coverage



# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
