version: 2.1

# Define the jobs we want to run for this project
jobs:
  working_directory: ~/project
  build:
    docker:
      - image: circleci/node:12.0.0-browsers
    steps:
      - checkout:
      - run: pwd
      - run: pwd
      - run: ls
      - run:
          command: yarn
          path: ~/project/client
      - run: yarn build
          command: yarn
          path: ~/project/client
  test:
    docker:
      - image: circleci/node:12.0.0-browsers
    steps:
      - checkout
      - run: source /.circleci/client_test.sh

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
